### ISSUE TITLE
How can we make transonic use a .pythranrc file?

### ISSUE THREAD

**Issue by jeanlaroche** [fluiddyn/transonic#2]
In my setup, pythran only works if I export XDG_CONFIG_HOME to point to a .pythranrc file (that specifies the location of my blas files).
I'm trying to use transonic but the compilation fails, apparently because blas can't be found, so I'm guessing the call to pythran from transonic does not forward that export.
Is there a way to fix that?

**Comment by jeanlaroche** [comment]
A bit of debugging. I'm able to compile the created .py file using pythran (with the export above), with an output name transonic explains. Then I can run the main code without a hitch.

BTW: Kudo on this work, it's really cool. I want to switch to using transonic, it will greatly simplify my work

**Comment by paugier** [comment]
> I want to switch to using transonic, it will greatly simplify my work

Great!

Regarding your issue, I've taken a look at it and I don't understand the problem. Pythran is called in transonic through 2 sub-processes (`subprocess.Popen` and then `subprocess.run`) but these sub-processes should inherit the environment of transonic, so pythran should see `XDG_CONFIG_HOME`.

A problem is that I can't reproduce your issue...

I added in `pythran/__init__.py`:
```
import os
print("XDG_CONFIG_HOME", os.environ["XDG_CONFIG_HOME"])
```
so that we can see the value of `XDG_CONFIG_HOME` seen by Pythran.

And I get the same result with and without Transonic (used with `transonic file_with_boost_decor.py -vv`):

```
XDG_CONFIG_HOME /home/users/augier3pi/.config
```

Any ideas what I should try to reproduce this issue ?

**Comment by jeanlaroche** [comment]
OK let me investigate and try to create a simpler case.

**Comment by jeanlaroche** [comment]
OK, I'm clarifying a few things.
- It's not "XDG_CONFIG_HOME" that's ignored, I was wrong. It's that if you have a .pythranrc in your home directory ~/.pythranrc, that rc file appears to be ignored by pythran when called by transonic.
- If however, I export export XDG_CONFIG_HOME=/Users/jlaroche then things work (but I have another problem I'll describe below).

**Comment by jeanlaroche** [comment]
Sorry about all the confusion above. I confirm that XDG_CONFIG_HOME works when pythran is called from transonic.
However, I have an issue in that the code does not compiled via transonic, but does when I simply call pythran on it. I'm going to try to make a small example of it.

**Comment by jeanlaroche** [comment]
OK here's a small example of my problem:
```
import numpy as np
from transonic import jit


@jit
def test(endFrm,NT,frmRange,corrs,scores,beatFrm,backtrack,tempoPenalty,beatPenalty,startFrm):
    candScores = np.zeros(NT)
    for frm in range(max(1,startFrm),endFrm):
        for ii in range(NT):
            frmSearch = np.arange(10,20)
            LSearch = len(frmSearch)
            A = candScores[0:LSearch]
            ddk = np.argmax(A)
            srcii = frmSearch[ddk] if ddk < LSearch else ii
            backtrack[ii,frm,0] = srcii
    return

test(20,20,np.ones((1000,2),dtype=int),np.zeros((200,200)),np.zeros((200,200)),np.zeros(200,dtype=int),np.zeros((200,200,2),dtype=int),.1,.1,0)

```
On MacOS, when running this in pythran, the pythranization of test is scheduled while the function continues (and exits). Then a compilation error occurs. https://pastebin.com/D2S6XNtS 

However, if I go and compile pythran -v ../Transonic/__jit__/test/test.py 
then things work just fine.

So there may be a difference in the way pythran is called by transonic, and the way I call it. Is there a way to pass -v to pythran so we can see what's going on in pythran?

**Comment by paugier** [comment]
On my computer (on Linux), your example works fine.

Can you please try to replace `@jit` by `@jit(native=False, xsimd=False)` ?

The jit decorator uses by default: 

```
In [2]: jit?                                                                    
Signature: jit(func=None, native=True, xsimd=True, openmp=False)
Docstring:
Decorator to record that the function has to be jit compiled
```

It makes sense for JIT compilation but I know that these options sometimes lead to Pythran errors.

We have to change these defaults to something more robust.

You can also try to manually compile with Pythran with `-march=native -USE_XSIMD`. Do you get the same Pythran error?

**Comment by jeanlaroche** [comment]
You are correct. It's the xsimd and openmp flags that cause a problem. This is a recurring issue on my mac, I didn't realize the flags were on by default. Thanks for pointing me in the right direction!
I'll let you close this issue if you think it needs to be or leave it open if you want to change the default!
Thanks again for transonic, it's really cool!

**Comment by paugier** [comment]
One last question on this issue, does it works with only `-march=native` or only `-USE_XSIMD`?

Anyway, we will change the default values for the next release. It's much better to follow the default Pythran choices.

**Comment by paugier** [comment]
It should be solved now. Do not hesitate to reopen if needed!
