### ISSUE TITLE
transonic recompiles over and over

### ISSUE THREAD

**Issue by jeanlaroche** [fluiddyn/transonic#3]
I have this function that I decorate with
```
from transonic import jit
@jit(native=False, xsimd=False)
```
When I run the calling code, transonic recompiles it at every call. The same file is generated each time:
```
INFO     Schedule pythranization of file /Users/jlaroche/Dev/Transonic/__jit__/model_tempo_inference/Conv2D.py
INFO:transonic:Schedule pythranization of file /Users/jlaroche/Dev/Transonic/__jit__/model_tempo_inference/Conv2D.py
Pythranizing /Users/jlaroche/Dev/Transonic/__jit__/model_tempo_inference/Conv2D.py
File /Users/jlaroche/Dev/Transonic/__jit__/model_tempo_inference/Conv2D_7fbf8e4323f9f9dee203c9fb3787f848_677a5fb2a459c4c7ad179a0b0529b121.cpython-36m-darwin.so created by Pythran
```
with no reported error. If I stop the execution, I can see the so file in the target directory.
Can you think of a reason why this is happening?

The function and the calling code are a bit long to reproduce here, but if needed I'll try to make a small case although this might be somewhat difficult.

**Comment by paugier** [comment]
Can you please try to manually import the extension module and to use the function that it provides?

```
cd /Users/jlaroche/Dev/Transonic/__jit__/model_tempo_inference
```
In IPython:
```
import Conv2D_7fbf8e4323f9f9dee203c9fb3787f848_677a5fb2a459c4c7ad179a0b0529b121 as Conv2D
Conv2D.your_function(...)
```

Does it work?

**Comment by jeanlaroche** [comment]
Yes, that works, I just checked...

**Comment by paugier** [comment]
It does not seem to be so simple then...

I can't reproduce the issue with this code:

```
import numpy as np
from transonic import jit, wait_for_all_extensions

@jit(native=False, xsimd=False)
def test(endFrm, NT, frmRange, corrs, scores, beatFrm, backtrack):
    candScores = np.zeros(NT)
    for frm in range(1, endFrm):
        for ii in range(NT):
            frmSearch = np.arange(10, 20)
            LSearch = len(frmSearch)
            A = candScores[0:LSearch]
            ddk = np.argmax(A)
            srcii = frmSearch[ddk] if ddk < LSearch else ii
            backtrack[ii, frm, 0] = srcii
    return


args = (
    20,
    20,
    np.ones((1000, 2), dtype=int),
    np.zeros((200, 200)),
    np.zeros((200, 200)),
    np.zeros(200, dtype=int),
    np.zeros((200, 200, 2), dtype=int),
)

print("call 0")
test(*args)

print("call 1")
test(*args)

wait_for_all_extensions()

print("call 2")
test(*args)
```

For me it gives
```
pierre@gre ~/tmp> transonic -cc bug_transonic.py -f
Remove directory /home/pierre/.transonic/__jit__/bug_transonic
pierre@gre ~/tmp> python bug_transonic.py 
call 0
INFO     Schedule pythranization of file /home/pierre/.transonic/__jit__/bug_transonic/test.py
call 1
Pythranizing /home/pierre/.transonic/__jit__/bug_transonic/test.py
File /home/pierre/.transonic/__jit__/bug_transonic/test_1cba29d063d6d71c07dd2e984019387e_fa8e193c9e7b2a104873cde5a93e4aff.cpython-37m-x86_64-linux-gnu.so created by Pythran
call 2
pierre@gre ~/tmp> python bug_transonic.py 
call 0
call 1
call 2
pierre@gre ~/tmp> python bug_transonic.py 
call 0
call 1
call 2
```

Can you please try and tell me if you reproduce the same issue with this code?

**Comment by paugier** [comment]
It could be a problem with the types of the arguments. Maybe you call the function different times with different types? It should work but the implementation may be buggy.

It would be interesting to look at the signature file:

```
cat /Users/jlaroche/Dev/Transonic/__jit__/model_tempo_inference/Conv2D.pythran
```

**Comment by jeanlaroche** [comment]
Here's the signature. Let me see if str isn't playing nice. I'll do a bit of debugging
export Conv2D(float32[:, :, :, :], float32[:, :, :, :], int list, str, str)

**Comment by jeanlaroche** [comment]
I'm not able to extract a small example. To help me debug, is there a way to stop the python processing while the compilation runs and wait for the so file to be created? I'm wondering if what I'm seeing isn't a result of the threaded compilation (my guess, because I think the python process continue while compilation occurs) and time-stamp on the so file?

**Comment by jeanlaroche** [comment]
NOTE: If I compile the function by running pythran with the expected output .so file, compilation works fine, but if I then call the main function, the compilation is re-triggered by transonic, with the same output file name.
Can you shed some light on the conditions under which a compilation is triggered? Or perhaps provide debugging info on that (i.e., a verbose mode that would show what transonic is doing and why it's doing it?)

**Comment by paugier** [comment]
> is there a way to stop the python processing while the compilation runs and wait for the so file to be created?

Something like this ?

```
from transonic import jit, wait_for_all_extensions

# blocks until all extensions have been compiled
wait_for_all_extensions()
```

**Comment by jeanlaroche** [comment]
Ah great, let me try that!

**Comment by paugier** [comment]
> Can you shed some light on the conditions under which a compilation is triggered?

The jit decorator is complicated. It is defined in 

https://bitbucket.org/fluiddyn/transonic/src/default/transonic/justintime.py

When the extension file exists (and corresponds to the right code), it can be recompiled if a TypeError is thrown by the function (what happens if a Pythran function is called with a wrong type).

This happens here: 
https://bitbucket.org/fluiddyn/transonic/src/e413478192ee0b55c9c75d3e1b10854e84fcbfbf/transonic/justintime.py#lines-405

**Comment by paugier** [comment]
> Or perhaps provide debugging info on that (i.e., a verbose mode that would show what transonic is doing and why it's doing it?)

It is not possible right now with `jit` but we'll add this "feature" soon.

**Comment by jeanlaroche** [comment]
I did more debugging. I put a breakpoint (pdb) before the call to Conv2D, to see whether the compiled version could be called without error, and I found out that the call fails. So contrary to what I said before (when I tried, compiling outside of the execution), the call fails with:
```
*** TypeError: Invalid call to pythranized function `Conv2D(float32[:, :, :, :] (reshaped), float32[:, :, :, :], int list, str, str)'
Candidates are:

    - Conv2D(float32[:,:,:,:], float32[:,:,:,:], int list, str, str)
```
So this explains why I'm getting a re-compilation over and over. I confirm that if I replace the first argument with x.copy() then everything works fine.
So the issue is caused by a type mismatch (something I'm finding happens quite a bit in pythran)

It would be good to have a way to throw an error when this happens, unless you expect it to happen often (for example, when recompiling for various input types). A -v flag could be super useful for this.

**Comment by paugier** [comment]
1. I'm going to add more log when there is a "TypeError: Invalid call to pythranized function" so that the user immediately understands what happens.

2. Actually, in your case, the error should not be catch because (i) Pythran is not able to deal with reshaped arrays and (ii) the Pythran signature produced with the given arguments is the same as the Pythran signature already used to compile the extension.

3. We need a way to activate the debug mode even with the jit decorator.

It's going to be much better after these 3 improvements so thank you for your report and the debugging!

**Comment by jeanlaroche** [comment]
Thanks!

**Comment by paugier** [comment]
Should be solved by https://bitbucket.org/fluiddyn/transonic/pull-requests/24

- TypeError raised for "(reshaped)"

- more blabla when calling jit function with new types

- `export TRANSONIC_DEBUG=1` for a more verbose mode

I even updated the git repository on Github :slightly_smiling_face:

**Comment by jeanlaroche** [comment]
Awesome! I guess I have to get the branch to test this. I'll do that.

**Comment by paugier** [comment]
I guess it's solved. Do not hesitate to reopen if there is still a problem.

**Comment by jeanlaroche** [comment]
Sorry I dropped the ball on that one. I'll let you know if I run into this issue again
