### ISSUE TITLE
transonic fails silently if pythran isn't installed...

### ISSUE THREAD

**Issue by jeanlaroche** [fluiddyn/transonic#4]
I know this is silly, but I ran into this. On a fresh install of python 3.6 where I forgot to install pythran, I tried to use transonic. I didn't get any failure alert, the normal python code ran and of course no compilation happened.
I'm guessing this is so because transonic can handle more than pythran...
Just wanted to alert you guys to that fact.
J.

**Comment by ashwinvis** [comment]
This is intended. And yes, `transonic` should do nothing if no "backends" are installed. Should a warning be emitted?

**Comment by jeanlaroche** [comment]
no no, as long as this is by design, we're all good.
